### ISSUE TITLE
Read from file instead of cin

### ISSUE THREAD

**Issue by g-radam** [GNVageesh/Bilobe#2]
Are you able to update Bilobe to read a file and execute it instead of reading from std::cin? A feature like this this would make the language a lot more usable in real-world scenarios. You could support reading from files OR reading from std::cin by using command line flags (Most compilers use command line flags to configure them). Example:

`./bilobe --cin` Will read from std::cin - so the user can type commands.
`./bilobe --file ./script.blb` Will read from the file _script.blb_ and execute it automatically! 

Thanks

**Comment by GNVageesh** [comment]
That's really a very idea... Thanks for bringing it out... that's gonna be the next thing to implemeny

**Comment by GNVageesh** [comment]
The feature has been added and now you can compile and run programs with the command `bilobe /path/to/file.bi`
Make sure to add the `.bi` file extension.
