### ISSUE TITLE
Update lnp to print a string OR a number

### ISSUE THREAD

**Issue by g-radam** [GNVageesh/Bilobe#3]
Currently LNP only prints a string. Can it be updated to accept a number? Example:
```
lnp("hello world")
lnp(1234)
```

Making the lnp function detect if its input is a string or a number is a great start, and can be expanded later for detecting if its a variable. Example:
`lnp(variable1)`

**Comment by GNVageesh** [comment]
Will implement it soon

**Comment by GNVageesh** [comment]
Well, now you can print number and string as well...
Strings - `lnp("Hello World")
Numbers - lnp(19376)
